name: Deployment
on:
  push: ~
  release:
    types:
      - published
jobs:
  test:
    uses: eps90/uuid-generator-chrome-extension/.github/workflows/test.yml@master
  pack:
    runs-on: ubuntu-latest
    needs:
      - build
      - e2e
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm install
        name: Install dependencies
      - name: Parse version
        uses: sergeysova/jq-action@v2
        id: ext_version
        with:
          cmd: jq .version package.json -r
      - name: Print the version
        run: 'echo "Version to be set: ${{ steps.ext_version.outputs.value }}"'
      - name: Build the application
        run: npm run-script build
        env:
          GENERATE_SOURCEMAP: false
          INLINE_RUNTIME_CHUNK: false
          REACT_APP_APP_VERSION: ${{ steps.ext_version.outputs.value }}
          REACT_APP_GOOGLE_ANALYTICS_KEY: ${{ secrets.GA_KEY }}
      - uses: montudor/action-zip@v1
        name: Pack the extension
        with:
          args: zip -qq -r main.zip build
      - name: Chrome Extension upload & publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: 'main.zip'
          app-id: ${{ secrets.EXTENSION_ID }}
          publish: false
